### ISSUE TITLE
iCade Rehaul (8bitdo, etc)

### ISSUE THREAD

**Issue by sevdestruct** [jasarien/Provenance#741]
Will use this for all incoming iCade related bugs, especially those concerning 8bitdo, which seem to be the favored ones since they are super retro. 

**Known Issues** (since i've wrote this a bunch of times in replies… thinking we start a FAQ section…):
- 8bitdo no longer officially supports iOS on current firmware (last i checked)
- to work on tvOS the firmware needs to be rolled back, in which case it registers as a keyboard which is a pre-MFi hack on 8bitdo's part, which comes with it's own limitations and known issues:
 - 8bitdos can't be used simulataneously (#523), Apple doesn't support more than one 'keyboard' connected to tvOS (probably iOS also, need confrimation) at a time. (guessing this goes same for other iCade controllers, if anyone wants to confirm, i only have 8bitdos (N30, F30 [both now discontinued in production]), SF30Pro) 
 - 8bitdos / iCade controllers cannot be used simultaneously with MFi controllers without breaking how the MFi inputs work, currently (#704) -- this may be resolveable, if someone has a solution, let us hear it, or submit a PR (please)
- 8bitdo Zero? requires remapping, not on Provenance side: #582 // …or @leolobato solution (unmerged, pending review): #713
 - _…will add more from comments, if reported._

To do:
 - [ ] Better 8bitdo Mapping - (consider suggestions in #679)
 - [ ] 8bitdo/iCade + MFi Simultaneously - (if possible) (insights in #704, and there is a running PR trying to solve this I think with #628)
 - [ ] 8btido Zero Support  - (PR, currently unmerged: #582 - seems to require some firmware changes and remapping?)…or @leolobato's PR: #713

Can't Fix:
 - 8bitdo + 8bitdo Simultaneous - (can't connect more than one 'keyboard' (pre-MFi hack by 8bitdo), which is how 8bitdo registers (not sure if that applies to all 8bitdo controllers, but they've otherwise stated they no longer support iOS in their documentation).

Please add to comments if you have new, additional or discrepant information to help…

**Comment by jasarien** [comment]
@sevdestruct you keep mentioning Leo for the 8bitdo zero PR — but it’s not his PR, it’s @justinweiss and @vincentsaluzzo that have submitted PRs for 8bitdo Zero support.

**Comment by sevdestruct** [comment]
i caught myself on taht actually in a Slack DM on it last time, not sure why i didn't have that straight.. will fix. thanks, @jasarien. Will update the issues that ref it. sorry for buggin @leolobato then, 😜

**Comment by sevdestruct** [comment]
- all fixed. deleting these comments in just a moment, thanks for the heads up, @jasarien

**Comment by justinweiss** [comment]
#582 doesn’t require any remapping or anything, that was a discussion in the comments for people trying to find a workaround. #713 includes #582, but fixes a bug when switching controllers, I think.

Is there a downgraded firmware available for the SF30 Pro that supports icade? I couldn’t find one, and if it exists, it would be worth linking to from the eventual FAQ.

**Comment by MarZab** [comment]
I tried do run 2 Zero's one in [START+B and the other in START+B+R](https://fccid.io/2AH7N-ZERO/User-Manual/Users-Manual-3293246) mode. 

They work at the same time and produce this keyboard output:
```
	PU	PR	PD	PL	SE	ST	Y	B	A	X	L	R
1	p	a	q	r	x	y	t	u	b	s	v	w
2	c	f	d	e	n	o	i	j	g	h	k	m
```

Could this be used ?

**Comment by sevdestruct** [comment]
@justinweiss: updated OP - as for the firmware for SF30Pro, i would have to go check against mine again.. will try to remember (maybe i can do this over the weekend) but i upgraded the firmware on mine and left it, seemed to work better with OpenEMu that way.. but i downgraded it once before, pretty sure.. so i think it's possible. current firmware wouldnt allow it to connect to to tvOS at all whatsoever, non detectable...

**Comment by sevdestruct** [comment]
@MarZab what are START+B , START+B+R modes?

**Comment by MarZab** [comment]
@sevdestruct just keyboard modes, but with seperate sets of key bindings

**Comment by womble25** [comment]
![51z6pld6eel _sl1024_](https://user-images.githubusercontent.com/17649707/38773640-af0055e6-4049-11e8-95e4-cd049d9e8e9c.jpg

requesting the gamesir 3gs be supported

**Comment by Tatzelworm** [comment]
https://drive.google.com/open?id=11ZojJr3pjj0lA1gO36gylslNR-1BVtI5

Or download.8bitdo.com for the entire 8bitdo file and directory rabbit hole. 

I have the nes30 pro and I have compiled a good lot of the various firmware updates and PDF guides for it from the 8bitdo site. I believe that the last icade compatible fw version is 2.2 which falls under the 'legacy' firmware updates. I have also added the various 1.7.1 extended fw releases that allow support for the original Nintendo Wii, ps3, or the retron5 I believe. And also have support for icade and Windows (though I don't remember if it has xinput or d input in those versions), and Android and I think osx.  I had most of these on my PC still, but I was able to just go to the 8bitdo website and navigate through their documents folder tree via download.8bitdo.com . You're able to go and download pretty much all of their devices fw updates and other information. It is not the most intuitive user experience, but it is still there.

**Comment by Grandtheft430** [comment]
@Tatzelworm i had been using buildstore too, but i've found their betas for Provenance are quite outdated. I've resolved my issue which i described above with building it via xcode (i mean i've updated to the latest beta possible).

**Comment by Tatzelworm** [comment]
@Grandtheft430 I currently have beta 1.5-7 that I installed end of April,lemme check, yeah April 30th. I like the changes to the pause menu and the ability to access your rom and bios directories from the actual phone, rather than just a USB or html/ftp access. I'm not sure how I feel about the start and select buttons being swapped while I'm playing pcengine games. I don't have the same issue with megadrive games and I haven't loaded any other systems yet, 32 dinky gigs just ain't enough. And if I recall, short of setting up another pain of a hackintosh or setting up an osx virtual machine, xcode is still an OSX only programming environment. And I built my tower with Windows in mind 😕 I don't have any other options for compiling and signing the code. I don't know, if you have any ideas for me I'm more than willing to give it a shot. So far as the actual programming though, I've definitely got to give anyone who has the ability to create anything like this props. I'm able to read hundreds of books and not think much of it, but I started with Ti Basic on my 83+ and then took a year of C++ and then a bit more than a year of Java when starting my first bachelors degree choice and I was murdered by Java. I'm can understand up to a point… and then I was just totally stuck. I'm more capable when it comes to electronics and computing from a hardware standpoint. 

And I have to apologize for this wall of text 🤐

,Will

**Comment by sevdestruct** [comment]
@Tatzelworm we don't support 3rd part builds of the app whatsoever. so stop supporting them, please. also we don't have the resources or funding to support beta iOS, and highly recommend you aren't using that or reporting bugs against it. as for the firmware for 8bitdo, yeah. got it. but should be available without hosting externally. i believe their rollbacks are available still as legacy on their support page.

…the buttons you are talking about should have - it doesnt help us to report bugs against old beta builds. please join the discord and talk there. 

Also, as for windows users, i just posted a new wiki about vitualizing macOS, with help from one of our Discord users who provided the steps. start there. 

—lastly, this isn't a discussion board. move to Discord—this topic is specifically for the 8bitdo support issues we are tracking and solving.

**Comment by Yamilquery** [comment]
Somebody knows how can I get work my 8Bitdo N64 controller with Proveance, is there some way to map it in easy way?

**Comment by Yamilquery** [comment]
A = uf
B = hr
C▲ = kp
C▼ = jn
C◀ = yt
C▶ = im
Z = lv
Start = og
L = kp
R = im
Left pad = aq
Right pad = dc
Up pad = we
Down pad = xz

**Comment by kriboogh** [comment]
Would it be possible to have:
- a settings option to map the buttons yourselve, so a settings page listing all “actions” (up, down, left, right, select, start, A, B, X, Y, R1, R2, L1, L2, save, reset, switch player). Then for each “action” you need to press a button on the controller you are using.
- provide a switch player menu (or button mapping), so at least in turnbased games, multiplayers can play with one controller (it just gets assigned to the next player)while in game, press “menu”.

One of the reasons is the N30 has B ”under” A, not next to each other like on the original controller, making it difficult when playing old NES games. An option to swap Y and B buttons would solve that (or making he entire controller mappable as suggested above.

**Comment by sevdestruct** [comment]
@kriboogh both of those are already suggested in other tickets. But in other news iCade might be dead (at least for tvOS specifically), thanks Apple.

**Comment by sevdestruct** [comment]
@kriboogh take a look at the new Controls doc, linked in wiki, i have been adjusting all the mappings based on a more physical based logic for a mapping methodology as relative to original layouts as possible, but have only gotten through MFi, not iCade yet, but will be also adjusting all iCade maps similarly/accordingly in time. 

Later I'll update the wiki here with the visual references of how the logic of the remaps has gone (they were previously shared on our Discord when i was workign on it)

**Comment by frntz** [comment]
Don't know if I have to put it here or on https://github.com/Provenance-Emu/Provenance/issues/871 but I have issue with the Provenance 1.4 with a FC30 Pro controller (Firmware Legacy v2).

**Comment by sevdestruct** [comment]
@frntz get yourself the latest beta if you are going to bug report. Also, please take a look at issue usage and FAQs on our wiki. Thank you.

**Comment by rbreaves** [comment]
I appear to be able sync 2 8bitdo controllers and an actual keyboard all at the same time and as someone mentioned earlier, the 8bitdo controller has two different key combos to hit during sync so that when it is in keyboard mode their mappings won't overlap. It makes no sense on why these controllers cannot technically be supported in 2 player mode. Would MFi and official support by 8bitdo be ideal? Sure, but like with the emulator itself - all these things are hacks.

I love what you guys have created, but it seems weird to me to only support mfi for 2 player when different keymaps for the 3.00 firmware could be easily enough supported.

This document mentions the sync modes for 2 players.
http://download.8bitdo.com/Manual/SNES30-Manual-v1.0.pdf

**Comment by JoeMatt** [comment]
I can't find any docs on what the keyboard input mappings are on the second controller. @rbreaves if you tell me what they are I can try to add it. I don't have a controller to test but I'm assuming if i just make an either or for each letter to button it should work. 

You can just pair the controllers and open an app with a text field and report back which button maps to which keyboard entry I can try it.

**Comment by rbreaves** [comment]
Thanks!! That'd be awesome, I definitely would prefer to use your emulator over RetroArch for most games.

For the 8bitdo SNES30 controllers in keyboard mode on firmware 3.00 (only firmware with iOS support before they dropped it)

Secondary Controller - START+B+R

B = u
Y = t
Select = x
Start = y
Up = p
Down = q
Left = r
Right = a
A = b
X = s
L = v
R = w

Primary Controller - START+B mode

B = j
Y = i
Select = n
Start = o
Up = c
Down = d
Left = e
Right = f
A = g
X = h
L = k
R = m

**Comment by JoeMatt** [comment]
I wasted a lot of time not realizing you can't upgrade past 3.0 and still work with iOS. I thought 2 play was a new feature but appears to be not. I moved the 2nd player 8bitdo support to it's own issue #1004

**Comment by rbreaves** [comment]
I apologize about that I should have led with what firmware version I was on instead of mentioning near the end of my initial post. 

I have been trying to find if 8bitdo has any interest in bringing back keyboard based support at the very least, but so far it looks like they want to support other platforms like the Switch so it leaves me wondering if they have limited space on the firmware or something. I am also not really finding much information on decompiling/reverse engineering their firmware to be updated with more sync options, but I am finding nothing so far.

Also it seems that the main reason they dropped iOS support is that 8bitdo could actually support MFi, but they won't because Apple requires that MFi should be the only supported protocol, and obviously that's a non-starter for them. It's still odd to remove the keyboard mode, because it seems like that is a cross-platform solution.

**Comment by JoeMatt** [comment]
Working on this in 

https://github.com/Provenance-Emu/Provenance/tree/feature/1004-8bitdo_2nd_player

Originally was looking just to add 2nd player mode for the controllers that support it (8Bitdo Zero, Ne30 maybe some others).

But hated the iCade code and did a wholesale conversion to swift so I can now do more advanced processing easier (non standard key codes, multiple chars, maybe happy chick we'll see)

**Comment by VrtlBrown** [comment]
I just got a 8bitdo SN30 controller and for the life of me can't get it to work with Provenance.

Its giving what looks to be the right keystrokes if I'm in the notes app and its working with iNDS so I'm confident I'm in the right mode.

I've tried all the settings and re-selecting 8bitdo in the Provenance app...

I'm on 1.5 beta 10
iOS 12.1 on a new iPad Pro

**Comment by franciscolourenco** [comment]
Is iCade + MFi currently supported or are there any outstanding bugs? thanks!

**Comment by zeronoun** [comment]
Here is a direct link to the final tvOS compatible SN30/SFC30 firmware, direct from 8bitdo:

[](http://download.8bitdo.com/Firmware/Controller/SN30+SF30/SN30+SF30_Firmware_Legacy_V3.00.zip)

**Comment by franciscolourenco** [comment]
@zeronoun thanks! With final you mean the last version which supports tvOS?

**Comment by zeronoun** [comment]
> @zeronoun thanks! With final you mean the last version which supports tvOS?

Yes. Following firmware 3.0, 8bitdo removed iOS/tvOS compatibility en lieu of Nintendo Switch support.
